# PYTORCH Y NUMPY

In [1]:
import numpy as np
import torch

In [3]:
# ARRAYS AND SUM OF ARRAYS IN NMPY
a= np.array([1, 2])
b= np.array([8,9])
c= a+b
c

array([ 9, 11])

In [4]:
#TENSORS AND SUM OF TENSORS IN PYTORCH
a= torch.tensor([1, 2])
b= torch.tensor([8,9])
c= a+b
c

tensor([ 9, 11])

In [9]:
#FROM NUMPY TO TENSOR
a= np.array([1, 2])
torch.from_numpy(a)

tensor([1, 2])

In [10]:
#FROM TORCH TO NUMPY
a= torch.tensor([1,2])
a.numpy()

array([1, 2])

## Tensors: n-dimensional numbers (includeing booleans) containers.

In [11]:
torch.tensor([[1,2],[2,1]])

tensor([[1, 2],
        [2, 1]])

In [12]:
torch.FloatTensor([[1,2],[2,1]])

tensor([[1., 2.],
        [2., 1.]])

In [13]:
torch.tensor([[1,2],[2,1]], dtype=torch.bool)

tensor([[True, True],
        [True, True]])

In [14]:
torch.rand(3,2)

tensor([[0.1788, 0.3867],
        [0.6389, 0.9938],
        [0.4644, 0.5432]])

In [15]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

- PYTORCH has a variety of usefull applications:

In [16]:
#SUMA
x= torch.tensor([[2,3], [1,2]])

x.sum()

tensor(8)

In [17]:
#TRANSPOSE 
x.t()

tensor([[2, 1],
        [3, 2]])

In [18]:
#GET SHAPE OF EACH DIMENSION
x.size()

torch.Size([2, 2])

In [20]:
#PERFORMING NEW OPERATIONS CRETES NEW TENSOR
y= torch.tensor([[2,2],[5,1]])
z= x.add(y)
z

tensor([[4, 5],
        [6, 3]])

In [21]:
#ALMOST ALL OPERATIONS HAVE AN IN-PLACE FUNTION FOLLOWED BY UNDER SCORE _
x.add_(y)
x

tensor([[4, 5],
        [6, 3]])

## runing on GPU
- You can run operations on the GPU
- Autograd: automatic differientiation
- A set of tools to build Neural Networks
- Inludes several packages for working with text or images

In [23]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cuda')

In [25]:
#PUT THE TENSOR ON THE GPU
x= torch.tensor([[2,3], [1,2]])
x=x.to(device)
x

tensor([[2, 3],
        [1, 2]], device='cuda:0')

In [26]:
# MAKE OPERATIONS WITH TENSORS IN THE GPU
y= torch.tensor([[2,2],[5,1]])
y=y.to(device)

z= x.add(y)

- Doing operations betwen CPU and GPU is not allowed 
- Size mismatch occurs often and is easy to fix: After each operation print the size¡
- Runing out of GPU memory 