# PYTORCH Y NUMPY

In [2]:
import numpy as np
import torch

In [4]:
# ARRAYS AND SUM OF ARRAYS IN NMPY
a= np.array([1, 2])
b= np.array([8,9])
c= a+b
c

array([ 9, 11])

In [6]:
#TENSORS AND SUM OF TENSORS IN PYTORCH
a= torch.tensor([1, 2])
b= torch.tensor([8,9])
c= a+b
c

tensor([ 9, 11])

In [7]:
#FROM NUMPY TO TENSOR
a= np.array([1, 2])
torch.from_numpy(a)

tensor([1, 2])

In [8]:
#FROM TORCH TO NUMPY
a= torch.tensor([1,2])
a.numpy()

array([1, 2])

## Tensors: n-dimensional numbers (includeing booleans) containers.

In [ ]:
torch.tensor([[1,2],[2,1]])

In [ ]:
torch.FloatTensor([[1,2],[2,1]])

In [ ]:
torch.tensor([[1,2],[2,1]], dtype=torch.bool)

In [ ]:
torch.rand(3,2)

In [ ]:
torch.ones(3,2)

- PYTORCH has a variety of usefull applications:

In [ ]:
#SUMA
x= torch.tensor([[2,3], [1,2]])

x.sum()

In [ ]:
#TRANSPOSE 
x.t()

In [ ]:
#GET SHAPE OF EACH DIMENSION
x.size()

In [ ]:
#PERFORMING NEW OPERATIONS CRETES NEW TENSOR
y= torch.tensor([[2,2],[5,1]])
z= x.add(y)
z

In [ ]:
#ALMOST ALL OPERATIONS HAVE AN IN-PLACE FUNTION FOLLOWED BY UNDER SCORE _
x.add_(y)
x

## runing on GPU
- You can run operations on the GPU
- Autograd: automatic differientiation
- A set of tools to build Neural Networks
- Inludes several packages for working with text or images

In [3]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cuda')

In [9]:
#PUT THE TENSOR ON THE GPU
x= torch.tensor([[2,3], [1,2]])
x=x.to(device)
x

tensor([[2, 3],
        [1, 2]], device='cuda:0')

In [10]:
# MAKE OPERATIONS WITH TENSORS IN THE GPU
y= torch.tensor([[2,2],[5,1]])
y=y.to(device)

z= x.add(y)

- Doing operations betwen CPU and GPU is not allowed 
- Size mismatch occurs often and is easy to fix: After each operation print the size¡
- Runing out of GPU memory 